"""initial schema with generic content items

Revision ID: a4a922fdfc63
Revises: 
Create Date: 2026-01-10 22:02:18.259169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4a922fdfc63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('pool_path', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reference_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_content_type_name', 'content_items', ['content_type', 'name'], unique=False)
    op.create_index('idx_content_type_name_version', 'content_items', ['content_type', 'name', 'version'], unique=False)
    op.create_index(op.f('ix_content_items_content_type'), 'content_items', ['content_type'], unique=False)
    op.create_index(op.f('ix_content_items_name'), 'content_items', ['name'], unique=False)
    op.create_index(op.f('ix_content_items_sha256'), 'content_items', ['sha256'], unique=True)
    op.create_index(op.f('ix_content_items_version'), 'content_items', ['version'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('feed', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('latest_path', sa.Text(), nullable=True),
    sa.Column('snapshots_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id')
    )
    op.create_table('views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('repo_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_views_name'), 'views', ['name'], unique=True)
    op.create_table('repository_content_items',
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('content_item_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('repository_id', 'content_item_id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_path', sa.Text(), nullable=True),
    sa.Column('package_count', sa.Integer(), nullable=False),
    sa.Column('total_size_bytes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'name', name='uq_snapshot_name')
    )
    op.create_index(op.f('ix_snapshots_name'), 'snapshots', ['name'], unique=False)
    op.create_table('view_repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('view_id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['view_id'], ['views.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('view_id', 'repository_id', name='uq_view_repository')
    )
    op.create_table('view_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('view_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('snapshot_ids', sa.JSON(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_path', sa.Text(), nullable=True),
    sa.Column('package_count', sa.Integer(), nullable=False),
    sa.Column('total_size_bytes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['view_id'], ['views.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('view_id', 'name', name='uq_view_snapshot_name')
    )
    op.create_index(op.f('ix_view_snapshots_name'), 'view_snapshots', ['name'], unique=False)
    op.create_table('snapshot_content_items',
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('content_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('snapshot_id', 'content_item_id')
    )
    op.create_table('sync_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('packages_added', sa.Integer(), nullable=False),
    sa.Column('packages_removed', sa.Integer(), nullable=False),
    sa.Column('packages_updated', sa.Integer(), nullable=False),
    sa.Column('bytes_downloaded', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_history')
    op.drop_table('snapshot_content_items')
    op.drop_index(op.f('ix_view_snapshots_name'), table_name='view_snapshots')
    op.drop_table('view_snapshots')
    op.drop_table('view_repositories')
    op.drop_index(op.f('ix_snapshots_name'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_table('repository_content_items')
    op.drop_index(op.f('ix_views_name'), table_name='views')
    op.drop_table('views')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_content_items_version'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_sha256'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_name'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_content_type'), table_name='content_items')
    op.drop_index('idx_content_type_name_version', table_name='content_items')
    op.drop_index('idx_content_type_name', table_name='content_items')
    op.drop_table('content_items')
    # ### end Alembic commands ###
