"""Add repository_files table and associations

Revision ID: 4ae7cc6b7243
Revises: a4a922fdfc63
Create Date: 2026-01-11 11:38:46.287103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae7cc6b7243'
down_revision: Union[str, None] = 'a4a922fdfc63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_category', sa.String(length=50), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('pool_path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('original_path', sa.Text(), nullable=False),
    sa.Column('file_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_repo_file_category', 'repository_files', ['file_category'], unique=False)
    op.create_index('idx_repo_file_type', 'repository_files', ['file_type'], unique=False)
    op.create_index(op.f('ix_repository_files_file_category'), 'repository_files', ['file_category'], unique=False)
    op.create_index(op.f('ix_repository_files_file_type'), 'repository_files', ['file_type'], unique=False)
    op.create_index(op.f('ix_repository_files_sha256'), 'repository_files', ['sha256'], unique=False)
    op.create_table('repository_repository_files',
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('repository_file_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_file_id'], ['repository_files.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('repository_id', 'repository_file_id')
    )
    op.create_table('snapshot_repository_files',
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('repository_file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repository_file_id'], ['repository_files.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('snapshot_id', 'repository_file_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshot_repository_files')
    op.drop_table('repository_repository_files')
    op.drop_index(op.f('ix_repository_files_sha256'), table_name='repository_files')
    op.drop_index(op.f('ix_repository_files_file_type'), table_name='repository_files')
    op.drop_index(op.f('ix_repository_files_file_category'), table_name='repository_files')
    op.drop_index('idx_repo_file_type', table_name='repository_files')
    op.drop_index('idx_repo_file_category', table_name='repository_files')
    op.drop_table('repository_files')
    # ### end Alembic commands ###
