"""add repository mode field

Revision ID: e190d159daac
Revises: 4ae7cc6b7243
Create Date: 2026-01-11 12:42:55.401365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e190d159daac'
down_revision: Union[str, None] = '4ae7cc6b7243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('mode', sa.Enum('MIRROR', 'FILTERED', 'HOSTED', name='repositorymode'), nullable=False, server_default='FILTERED'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'mode')
    # ### end Alembic commands ###
